sudo: required
services:
  - docker

before_install:
  - docker build -t app/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run app/react-test npm tet -- --coverage

after_success:
  - docker build -t app/react-client ./client
  - docker build -t app/react-nginx ./nginx
  - docker build -t app/react-server ./server
  - docker build -t app/react-worker ./worker
  #Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push app/react-client
  - docker push app/react-nginx
  - docker push app/react-server
  - docker push app/react-worker